@extends('Managerzone.layout')

@section('title', 'Reports - Inventory Pro')
@section('page_title', 'System Reports')
@section('page_subtitle', 'Generate, view, and export comprehensive reports')

@section('content')
<div class="tables-row" style="grid-template-columns: 1fr 1fr 1fr; margin-bottom: 24px;">
    <!-- Sales Report -->
    <div class="panel">
        <div class="panel-header">
            <h2 class="panel-title"><i class="ph ph-currency-dollar"></i> SALES REPORT</h2>
        </div>
        <p style="font-size: 13px; color: var(--text-gray); margin-bottom: 15px;">Comprehensive breakdown of sales revenue, top products, and customer trends.</p>
        <div style="display: flex; flex-direction: column; gap: 10px;">
            <select class="select-filter">
                <option>Last 30 Days</option>
                <option>This Quarter</option>
                <option>Year to Date</option>
            </select>
            <div style="display: flex; gap: 10px; margin-top: 10px;">
                <button class="quick-actions-btn" style="flex: 1; margin: 0; background: var(--bg-body);"><i class="ph ph-file-pdf"></i> PDF</button>
                <button class="quick-actions-btn" style="flex: 1; margin: 0; background: var(--success-light); color: var(--success); border-color: var(--success);"><i class="ph ph-file-xls"></i> Excel</button>
            </div>
        </div>
    </div>

    <!-- Inventory Report -->
    <div class="panel">
        <div class="panel-header">
            <h2 class="panel-title"><i class="ph ph-package"></i> INVENTORY REPORT</h2>
        </div>
        <p style="font-size: 13px; color: var(--text-gray); margin-bottom: 15px;">Stock valuation, movement history, and low stock analysis.</p>
        <div style="display: flex; flex-direction: column; gap: 10px;">
            <select class="select-filter">
                <option>All Warehouses</option>
                <option>Main Warehouse</option>
                <option>East Warehouse</option>
            </select>
            <div style="display: flex; gap: 10px; margin-top: 10px;">
                <button class="quick-actions-btn" style="flex: 1; margin: 0; background: var(--bg-body);"><i class="ph ph-file-pdf"></i> PDF</button>
                <button class="quick-actions-btn" style="flex: 1; margin: 0; background: var(--success-light); color: var(--success); border-color: var(--success);"><i class="ph ph-file-xls"></i> Excel</button>
            </div>
        </div>
    </div>

    <!-- Production Report -->
    <div class="panel">
        <div class="panel-header">
            <h2 class="panel-title"><i class="ph ph-factory"></i> PRODUCTION REPORT</h2>
        </div>
        <p style="font-size: 13px; color: var(--text-gray); margin-bottom: 15px;">Efficiency metrics, delay analysis, and output tracking.</p>
        <div style="display: flex; flex-direction: column; gap: 10px;">
            <select class="select-filter">
                <option>This Month</option>
                <option>Previous Month</option>
            </select>
            <div style="display: flex; gap: 10px; margin-top: 10px;">
                <button class="quick-actions-btn" style="flex: 1; margin: 0; background: var(--bg-body);"><i class="ph ph-file-pdf"></i> PDF</button>
                <button class="quick-actions-btn" style="flex: 1; margin: 0; background: var(--success-light); color: var(--success); border-color: var(--success);"><i class="ph ph-file-xls"></i> Excel</button>
            </div>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-header">
        <h2 class="panel-title">RECENT GENERATED REPORTS</h2>
    </div>
    <table>
        <thead>
            <tr>
                <th>Report Name</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Format</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="font-weight: 500;">Q1 Sales Summary</td>
                <td>John Manager</td>
                <td>May 20, 2025</td>
                <td><span style="color: var(--danger); font-weight: 600;">PDF</span></td>
                <td><a href="#" class="panel-action">Download</a></td>
            </tr>
            <tr>
                <td style="font-weight: 500;">April Inventory Valuation</td>
                <td>Emily Davis</td>
                <td>May 02, 2025</td>
                <td><span style="color: var(--success); font-weight: 600;">EXCEL</span></td>
                <td><a href="#" class="panel-action">Download</a></td>
            </tr>
        </tbody>
    </table>
</div>
@endsection
